
spring: 
  profiles: 
    active: 
       -dev
---
server:
 port: 8001
 
spring:
  profiles: dev  #开发环境
  application:
    name:  microservicecloud-config-client-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud01?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  typeAliasesPackage: com.moye.springcloud.entity
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-config-client-dept
    prefer-ip-address: true
---
server:
 port: 8001
 
spring:
 profiles: test
 application: 
  name: microservicecloud-config-client-dept
 datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud01?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  typeAliasesPackage: com.moye.springcloud.entity
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-config-client-dept
    prefer-ip-address: true
   